import { MissionConfig, MissionId } from '../../types/game';

export const MISSIONS: MissionConfig[] = [
  {
    id: 'mission_1_suburb_recon',
    number: 1,
    title: 'OPERATION SUBURB RECON',
    codename: 'SHADOW PERIMETER',
    tagline: 'Neighborhood Encampment Sweep',
    arena: 'industrial',
    arenaName: 'SUBURBAN RESIDENTIAL TOWN',
    briefing: 'Hostile insurgent scouts have set up frontline combat encampments in the residential sector. Sweep the neighborhood, eliminate 20 hostile combatants, and detonate 2 enemy explosive supply caches.',
    primaryObjective: 'Eliminate 20 hostiles and destroy 2 explosive barrels',
    targetKills: 20,
    targetBarrels: 2,
    targetWaves: 3,
    rewardCoins: 150,
    rewardScore: 2500,
    difficulty: 'RECON',
    badge: '🎖️ RECON OPERATIVE',
    badgeColor: '#22c55e',
    accentColor: '#10b981'
  },
  {
    id: 'mission_2_neon_lockdown',
    number: 2,
    title: 'OPERATION NEON LOCKDOWN',
    codename: 'CYBER SIEGE',
    tagline: 'Downtown Avenue Counter-Siege',
    arena: 'neon_city',
    arenaName: 'DOWNTOWN METROPOLIS',
    briefing: 'A rogue cybernetic syndicate has placed the downtown commercial avenue under heavy siege with agile cyber sprinters and suicide drone units. Engage optical zoom to neutralize 30 hostiles across 4 escalating combat waves.',
    primaryObjective: 'Survive 4 combat waves & neutralize 30 syndicate hostiles',
    targetKills: 30,
    targetWaves: 4,
    rewardCoins: 250,
    rewardScore: 5000,
    difficulty: 'TACTICAL',
    badge: '⚡ URBAN HUNTER',
    badgeColor: '#0284c7',
    accentColor: '#0ea5e9'
  },
  {
    id: 'mission_3_desert_mirage',
    number: 3,
    title: 'OPERATION DESERT MIRAGE',
    codename: 'LONG-RANGE VIPER',
    tagline: 'Adobe Terraces Precision Duel',
    arena: 'desert',
    arenaName: 'DESERT OASIS SETTLEMENT',
    briefing: 'Enemy marksmen and demolition squads are deeply entrenched high atop the desert adobe terraces. Take position, engage Tactical Zoom (Z key) to lock onto critical sensors, and achieve 8 headshots while clearing 25 hostiles.',
    primaryObjective: 'Achieve 8 critical headshots & eliminate 25 desert hostiles',
    targetKills: 25,
    targetHeadshots: 8,
    targetWaves: 4,
    rewardCoins: 350,
    rewardScore: 7500,
    difficulty: 'VETERAN',
    badge: '🎯 MASTER MARKSMAN',
    badgeColor: '#d97706',
    accentColor: '#f59e0b'
  },
  {
    id: 'mission_4_titan_protocol',
    number: 4,
    title: 'OPERATION TITAN PROTOCOL',
    codename: 'COLOSSUS PURGE',
    tagline: 'Warehouse Depot Goliath Infiltration',
    arena: 'space_station',
    arenaName: 'FREIGHT LOGISTICS & WAREHOUSES',
    briefing: 'Deep within the freight container depot, the supreme mechanized combat war machine—the Cyber Titan Goliath—has activated. Breach the depot, eliminate the heavy juggernaut guard, and eradicate the Goliath Titan.',
    primaryObjective: 'Destroy the prototype GOLIATH MECH TITAN boss',
    targetKills: 20,
    hasBoss: true,
    targetWaves: 3,
    rewardCoins: 500,
    rewardScore: 12000,
    difficulty: 'EXTREME',
    badge: '🛡️ TITAN SLAYER',
    badgeColor: '#e11d48',
    accentColor: '#f43f5e'
  },
  {
    id: 'mission_5_chrono_surge',
    number: 5,
    title: 'OPERATION CHRONO SURGE',
    codename: 'ZERO-HOUR OVERDRIVE',
    tagline: '90-Second EMP Gauntlet',
    arena: 'neon_city',
    arenaName: 'DOWNTOWN METROPOLIS',
    briefing: 'A localized EMP countdown is active! You have strictly limited time to eliminate 35 hostiles and halt their command signals. Every kill awards +4 bonus seconds to your timer. Move fast and strike relentlessly.',
    primaryObjective: 'Eliminate 35 hostiles before the 90s EMP countdown expires',
    targetKills: 35,
    timeLimit: 90,
    rewardCoins: 600,
    rewardScore: 15000,
    difficulty: 'APEX',
    badge: '⌛ SPEED OVERDRIVE',
    badgeColor: '#9333ea',
    accentColor: '#a855f7'
  }
];

export function getMissionById(id: MissionId | string): MissionConfig | undefined {
  return MISSIONS.find(m => m.id === id);
}
